version: "3.9"

services:
  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kolkata
    volumes:
      - ./config:/config
      - ${DOWNLOAD_PATH}:/downloads
      - ${MEDIA_PATH}:/media
    ports:
      - 8989:8989
    networks:
      - server-main
    restart: unless-stopped

networks:
  server-main:
    external: true
