version: "3.9"

services:
  qbittorrent:
    image: linuxserver/qbittorrent
    container_name: qbittorrent
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kolkata
      - WEBUI_PORT=8080
    volumes:
      - ./config:/config
      - ${DOWNLOAD_PATH}:/downloads
    restart: unless-stopped


