version: '3'
services:
  app:
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: nginx
    restart: unless-stopped
    dns:
      - 1.1.1.1
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    networks:
      - server-main
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt


networks:
  server-main:
    external: true
