version: "3.9"

services:
  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    environment:
      - PUID=1000                # your user ID
      - PGID=1000                # your group ID
      - TZ=Asia/Kolkata
    volumes:
      - ./config:/config
      - /home/karthikeyan/Media:/media   # your media folder
    networks:
      - server-main
    ports:
      - 6767:6767
    restart: unless-stopped

networks:
  server-main:
    external: true
